apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: go-hpa
  labels:
    app: go-hpa
    version: "1"
    env: staging
    tier: backend
    role: hpa

spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: go-server
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 60

