apiVersion: v1
kind: Service
metadata:
  name: go-service
  labels:
    app: go-service
    version: "1"
    env: staging
    tier: backend
    role: service
spec:
  selector:
    app: go-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

