### Send POST request to add advertisement
POST {{HOST_URL}}/api/{{API_VERSION}}/ad
Content-Type: application/json

{
  "title": "AD 55",
  "startAt": "2023-12-10T03:00:00.000Z",
  "endAt":"2023-12-31T16:00:00.000Z",
  "conditions": {
    "ageStart": 20,
    "ageEnd": 30,
    "country" : ["TW", "JP"],
    "platform": ["android", "ios"]
  }
}